const { normalizeError } = require('../../../../common/error/frontend')

const _isStandardError = err => {
  return (
    err instanceof TypeError ||
    err instanceof ReferenceError ||
    err instanceof SyntaxError ||
    err instanceof RangeError ||
    err instanceof URIError
  )
}

const _beautifyMessage = msg => (msg.endsWith('.') ? msg : `${msg}.`)

const _buildRootCauseMessage = (message, rootCause) => {
  if (rootCause) {
    message = `${_beautifyMessage(message)} ${_beautifyMessage(rootCause.message)}`

    if (typeof rootCause.getRootCause === 'function') {
      message = _buildRootCauseMessage(message, rootCause.getRootCause())
    }
  }

  return message
}

// const _getRootCauseDeep = err => {
//   const rootCause = err.getRootCause && err.getRootCause()
//   if (rootCause && rootCause.getRootCause) {
//     rootCause.innererror = _getRootCauseDeep(rootCause)
//     delete rootCause.getRootCause
//   }
//   return rootCause
// }

/**
 * Custom error handler.
 * Crashes the node instance, if not deactivated.
 * @param {Boolean} crashOnError
 * @param crashOnError
 * @returns {Function}
 */
const getErrorHandler = (crashOnError = true) => {
  return (odataReq, odataRes, next, err) => {
    // REVISIT: crashOnError
    /* istanbul ignore if */
    if (_isStandardError(err) && crashOnError) {
      // Throwing async will circumvent the odata-v4 catch and crash the Node.js instance.
      // FIXME: Please let's fix the root cause in okra instead of such work-arounds
      setImmediate(() => {
        throw err
      })

      return
    }

    if (err.getRootCause && typeof err.getRootCause === 'function') {
      // > an OKRA error
      // REVISIT: use innererror instead of message = _buildRootCauseMessage once OKRA lets innererror through
      return next(
        null,
        Object.assign(err, {
          code: err.code || 'null',
          // innererror: _getRootCauseDeep(err),
          message: _buildRootCauseMessage(err.message, err.getRootCause())
        })
      )
    }

    // get req for i18n
    let req
    const isBatch = odataReq.getBatchApplicationData() !== null
    if (isBatch) {
      req = odataReq.getBatchApplicationData().req
    } else {
      req = odataReq.getIncomingRequest()
    }

    const { error, statusCode } = normalizeError(err, req)

    next(null, Object.assign(error, { statusCode }))
  }
}

module.exports = getErrorHandler
